<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="11" passed="9" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-31T13:22:37 IST" name="Suite" finished-at="2023-05-31T13:22:56 IST" duration-ms="18954">
    <groups>
    </groups>
    <test started-at="2023-05-31T13:22:37 IST" name="Test" finished-at="2023-05-31T13:22:56 IST" duration-ms="18954">
      <class name="com.notesapi.tests.UsersTests">
        <test-method signature="createNewUser()[pri:0, instance:com.notesapi.tests.UsersTests@34b7ac2f]" started-at="2023-05-31T13:22:38 IST" name="createNewUser" finished-at="2023-05-31T13:22:46 IST" duration-ms="8025" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewUser -->
        <test-method signature="performLogin(org.testng.ITestContext)[pri:1, instance:com.notesapi.tests.UsersTests@34b7ac2f]" started-at="2023-05-31T13:22:46 IST" name="performLogin" finished-at="2023-05-31T13:22:47 IST" duration-ms="799" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@2314cd97]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [201] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [201] but found [200]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at org.testng.Assert.assertEquals(Assert.java:1274)
at com.notesapi.tests.UsersTests.performLogin(UsersTests.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- performLogin -->
        <test-method signature="retrieveUserInfo()[pri:2, instance:com.notesapi.tests.UsersTests@34b7ac2f]" started-at="2023-05-31T13:22:47 IST" name="retrieveUserInfo" finished-at="2023-05-31T13:22:50 IST" duration-ms="3024" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- retrieveUserInfo -->
        <test-method signature="editUserInfo()[pri:3, instance:com.notesapi.tests.UsersTests@34b7ac2f]" started-at="2023-05-31T13:22:50 IST" name="editUserInfo" finished-at="2023-05-31T13:22:51 IST" duration-ms="491" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at org.testng.Assert.assertEquals(Assert.java:1274)
at com.notesapi.tests.UsersTests.editUserInfo(UsersTests.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editUserInfo -->
        <test-method signature="editUserPassword()[pri:4, instance:com.notesapi.tests.UsersTests@34b7ac2f]" started-at="2023-05-31T13:22:51 IST" name="editUserPassword" finished-at="2023-05-31T13:22:51 IST" duration-ms="925" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editUserPassword -->
      </class> <!-- com.notesapi.tests.UsersTests -->
      <class name="com.notesapi.tests.NotesTests">
        <test-method is-config="true" signature="beforeClass(org.testng.ITestContext)[pri:0, instance:com.notesapi.tests.NotesTests@28eaa59a]" started-at="2023-05-31T13:22:51 IST" name="beforeClass" finished-at="2023-05-31T13:22:51 IST" duration-ms="9" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@2314cd97]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="createNewNote()[pri:0, instance:com.notesapi.tests.NotesTests@28eaa59a]" started-at="2023-05-31T13:22:51 IST" name="createNewNote" finished-at="2023-05-31T13:22:52 IST" duration-ms="860" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewNote -->
        <test-method signature="retrieveNote()[pri:1, instance:com.notesapi.tests.NotesTests@28eaa59a]" started-at="2023-05-31T13:22:52 IST" name="retrieveNote" finished-at="2023-05-31T13:22:53 IST" duration-ms="582" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- retrieveNote -->
        <test-method signature="retrieveNoteById()[pri:2, instance:com.notesapi.tests.NotesTests@28eaa59a]" started-at="2023-05-31T13:22:53 IST" name="retrieveNoteById" finished-at="2023-05-31T13:22:54 IST" duration-ms="839" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- retrieveNoteById -->
        <test-method signature="updateExistingNote()[pri:3, instance:com.notesapi.tests.NotesTests@28eaa59a]" started-at="2023-05-31T13:22:54 IST" name="updateExistingNote" finished-at="2023-05-31T13:22:54 IST" duration-ms="698" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateExistingNote -->
        <test-method signature="updateCompleteStatusOfNote()[pri:4, instance:com.notesapi.tests.NotesTests@28eaa59a]" started-at="2023-05-31T13:22:54 IST" name="updateCompleteStatusOfNote" finished-at="2023-05-31T13:22:55 IST" duration-ms="745" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateCompleteStatusOfNote -->
        <test-method signature="deleteNoteById()[pri:5, instance:com.notesapi.tests.NotesTests@28eaa59a]" started-at="2023-05-31T13:22:55 IST" name="deleteNoteById" finished-at="2023-05-31T13:22:56 IST" duration-ms="728" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteNoteById -->
      </class> <!-- com.notesapi.tests.NotesTests -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
